### ISSUE TITLE
v0.5+ features

### ISSUE THREAD

**Issue by kbarbary** [kbarbary/sep#14]
## Feature list for v0.5.0

- [x] mask option in `sep.extract()`
- [x] Output objects' member pixels in `sep.extract()`
- [x] improve filtering with noise array (@kboone).

## Won't implement

- make cleaning & deblending available as separate routines (too much work, no obvious demand)
- Neighbor object masking in aperture functions (difficult because it mixes "member pixels" & apertures; no obvious demand)

**Comment by BrunoSanchez** [comment]
Hi!

I wonder if there are plans for including CLASS_STAR 
to differentiate between point source objects and 
extended objects.

Thanks!
Bruno

**Comment by kbarbary** [comment]
At a quick glance, the SExtractor code for CLASS_STAR looks fairly simple (in `src/analyse.c` in the SExtractor repository)... its only about 20 lines. However, I was under the impression that this wasn't really a great metric anyway, so I'm not sure of the value in including it here.

I'd probably accept a PR implementing it though :)

**Comment by benjaminrose** [comment]
Sep is so much easier to use the SExtrator, thanks! But I need to define the edges of my objects on an absolute scale (surface brightness:) rather then a relative scale of n*(background rms). 

Is this currently possible using sep or is it a feature that needs to be added?

**Comment by kbarbary** [comment]
@benjaminrose Thanks! If you don't pass an `err` argument to `sep.extract()`, the threshold will be interpreted as an absolute threshold: only pixels with value above `thresh` will be included in an object. (caveat: which pixels are "above threshold" is also affected by convolution. Turn it off for this to be strictly true.)

Is that what you're looking for?

**Comment by kbarbary** [comment]
Closing this as all planned features (masking & segmentation map) are now implemented in v0.5.0.
