### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by mkuemmel** [kbarbary/sep#17]
Tried to buyild sep, but pretty soon comes the error below. My components are:
OS: ubuntu 12.04 LTS
python 2.7.3
numpy 1.6.1
cython0.15.1

Compiling the C-sources with scons does work.

----------------------------------------------------------------------------------------------------------------------------------------------
Compiling sep.pyx because it changed.
Cythonizing sep.pyx

Error compiling Cython file:
------------------------------------------------------------
...
                       void **ptr, void **eptr, void **mptr, float *scalarerr,
                       short *inflag) except -1:
    """Helper function for functions accepting data, error & mask arrays"""

    cdef int ew, eh, mw, mh
    cdef np.uint8_t[:,:] buf, ebuf, mbuf
                   ^
------------------------------------------------------------

sep.pyx:244:20: Expected an identifier or literal
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    extensions = cythonize(extensions)
  File "/usr/lib/pymodules/python2.7/Cython/Build/Dependencies.py", line 517, in cythonize
    cythonize_one(pyx_file, c_file, quiet, options)
  File "/usr/lib/pymodules/python2.7/Cython/Build/Dependencies.py", line 540, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: sep.pyx

**Comment by kbarbary** [comment]
Thanks for reporting this. I *think* this is because the typed memory view syntax `np.uint8_t[:, :]` was only introduced in Cython 0.16, but I'll dig a bit to be sure about that.

https://github.com/cython/cython/wiki/ReleaseNotes-0.16 (see "Features")

**Comment by mkuemmel** [comment]
I can confirm that it compiles with a newer version of Cython (0.21.2). I am closing the issue now.

**Comment by kbarbary** [comment]
Great! I'll add the requirement Cython>=0.16 to the install instructions.
