### ISSUE TITLE
Support for windowed parameters

### ISSUE THREAD

**Issue by ofors** [kbarbary/sep#18]
@kbarbary , it would be really nice if sep could support windowed parameters such as XWIN_IMAGE, YWIN_IMAGE.
Is there any chance you could release a new version with this new support?

Thanks so much,

Octavi.

PS: I don't pull a request because I'll have my hands full over the next weeks.

**Comment by kbarbary** [comment]
If I find some time, sure! No promises though. In the mean time, if anyone else happens to be eager to take a crack at this, the relevant C code in SourceExtractor is the `compute_winpos()` function in `winpos.c`.

**Comment by ofors** [comment]
Thanks @kbarbary for giving a try.

**Comment by kbarbary** [comment]
This is now implemented in sep v0.4.0, just released today. See the [`sep.winpos()` function API](http://sep.readthedocs.org/en/v0.4.x/api/sep.winpos.html) and a [blurb about mimicing SExtractor in the docs](http://sep.readthedocs.org/en/v0.4.x/apertures.html#equivalent-of-xwin-image-ywin-image-in-source-extractor).

Please do report if you have any problems with sep v0.4.0.

**Comment by ofors** [comment]
Thanks so much @kbarbary . I'll give a try in the next week or so.
