### ISSUE TITLE
Test failure on Windows 

### ISSUE THREAD

**Issue by mwcraig** [kbarbary/sep#31]
On Windows I get a failure at [L79 of test.py](https://github.com/kbarbary/sep/blob/master/test.py#L79) because one more source is detected on Windows than is in the reference catalog. The extra object is at index 40 in the sep catalog in the test.

**Comment by kbarbary** [comment]
As with #30, this also seems to have been due to deblending. Fixed by turning off deblending in the test (see #32, specifically b58a565).

Thanks, Matt! I'll release a new version with these changes.
