### ISSUE TITLE
Malloc crash in background.rms

### ISSUE THREAD

**Issue by cmccully** [kbarbary/sep#38]
When running the following:
from astropy.io import fits
import sep
hdu = fits.open('lsc1m009-fl03-20160410-0085-e91.fits')
data = hdu[0].data.copy().byteswap(True).newbyteorder().copy()
bkg = sep.Background(data, bw=64, bh=64, fw=3, fh=3)
bkg.rms()
python(40487,0x7fff79a9d000) malloc: *** error for object 0x10b682780: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

**Comment by kbarbary** [comment]
Interesting. I guess this is coming from Python's malloc. Can you send me the file to test with?

**Comment by kbarbary** [comment]
I can also reproduce this with just about any array it seems. I must have messed something up while refactoring and there wasn't a test for rms()...
