### ISSUE TITLE
SExtractor uses minimum sig when computing windowed positions

### ISSUE THREAD

**Issue by kbarbary** [kbarbary/sep#40]
There are some discrepancies in windowed position parameters for objects with small Kron radii. This was originally discussed in #37.

It looks like SExtractor effectively sets a minimum for the `sig` parameter. In the original codebase, in `compute_winpos`, `sig` is set to

```c
sig = obj2->hl_radius*2.0/2.35; /* From half-FWHM to sigma */
```

when computing the half-light radius, there are checks on the minimum and maximum value

```c
    if (obj2->hl_radius < GROWTH_MINHLRAD)
      obj2->hl_radius = GROWTH_MINHLRAD;
    }
```

`GROWTH_MINHLRAD` is 0.5 pixels, so the minimum `sig` value is 0.5*2.0/2.35. We should try setting this in the tests to see if it resolves the discrepancy.

Assuming it does, we can either simply document the SExtractor behavior, or hard-code this minimum in `sep.winpos` and add documentation about it.

**Comment by fred3m** [comment]
I'm not sure whether this is a related issue or not but I've noticed that sometimes the windowed positions can drift from the image positions as far as several arcmin to another object (in semi-crowded regions).

 I put a check in my code to ignore the windowed position if the change in position is more than half the distance to the nearest neighbor or further than the aperture radius, whichever is smaller (and flag sources that had a bad windowed position). Let me know if you'd like me to update SEP with my changes or open another issue.

**Comment by kbarbary** [comment]
@fred3m This sounds like a separate issue. Can you open a new one?

**Comment by fred3m** [comment]
Sure. I created a couple of ipython notebooks demonstrating the issue and created ticket #45.
