### ISSUE TITLE
Having a mask when calculating the Kron radius leads to strange results

### ISSUE THREAD

**Issue by cmccully** [kbarbary/sep#41]
When using a mask in the kron radius function, the first few values I calculate are 1e-320 and the like. Without the mask, things work fine. This seems like a memory mapping error. It would also be useful to double check the mask keyword works correctly flux_radius, sum_ellipse, and winpos.

**Comment by kbarbary** [comment]
You were probably using a boolean array as a mask. There was a missing conversion function for booleans. The C code raises an error about an unsupported data type, but I had forgotten to check the C return status in the Python wrapper, so it went unnoticed.
