### ISSUE TITLE
sep.extract() TypeError: can't concat bytes to str - Python 3.5.1

### ISSUE THREAD

**Issue by jmccormac01** [kbarbary/sep#43]
Hi, I've been running through a simple example of source detection with sep today using python 3.5.1 and sep 0.5.2. I came across a TypeError when trying to extract sources from an image. 

```python
>>> objects = sep.extract(data,thresh)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sep.pyx", line 694, in sep.extract (sep.c:6883)
  File "sep.pyx", line 255, in sep._assert_ok (sep.c:3342)
TypeError: can't concat bytes to str
```

A colleague pointed out that this might be a python2 vs python3 issue. I tried running the same code in python2.7 and I got the following error:

```python
>>> objects = sep.extract(data,thresh)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sep.pyx", line 694, in sep.extract (sep.c:6883)
  File "sep.pyx", line 255, in sep._assert_ok (sep.c:3357)
Exception: internal pixel buffer full: The limit of 300000 active object pixels over the detection threshold was reached. Check that the image is background subtracted and the detection threshold is not too low. If you need to increase the limit, use sep.set_extract_pixstack.
```

It turns out that I had not subtracted off the background and my threshold was too low, so it was flagging everything and running out of space in the pixel buffer. I've fixed my problem by subtracting the background from ```data``` before extraction, but I thought I should point out the issue with the error message being mangled on python3.

**Comment by kbarbary** [comment]
This should be fixed on master. I should do a new release soon!

**Comment by jmccormac01** [comment]
ah, I had installed via pip. Thanks.
