### ISSUE TITLE
Measuring the max pixel value in sep.sum_* methods 

### ISSUE THREAD

**Issue by jmccormac01** [kbarbary/sep#44]
This is not an issue, but more of a question (I'm not sure how else to ask it). Is it possible to measure the max pixel value in an extracted aperture using the ```sep.sum_*``` methods? I know I can get it if I extract all the stars in the image with ```sep.extract``` but this seems quite a roundabout way to get it when I already have the aperture positions from another method (WCS etc). 

As a side note, I think there might be a typo in the RTD API page for ```sep.extract```. Should this:

```
xpeak, ypeak (int) Coordinate of convolved peak pixel.
```

be:

```
xpeak, ypeak (int) Coordinate of unconvolved peak pixel.
```

to match the ```peak``` and ```cpeak``` definitions?

**Comment by kbarbary** [comment]
The `sum_*` methods won't do this.  I would probably just get the peak value in a *rectangle* around the object with normal numpy methods, like `np.max(data[int(y-r):int(y+r), int(x-r):int(x+r)])`.

You're right about the docstring, thanks for pointing it out!

**Comment by jmccormac01** [comment]
Sometimes the simplest solution is the hardest to see :) I shall use numpy to get the max value. Thanks.
