### ISSUE TITLE
Excluding stars from sky background level correction

### ISSUE THREAD

**Issue by jmccormac01** [kbarbary/sep#48]
Hi,
I've been wondering for a while if SEP takes into account stars that might lie in the sky background annulus when using ```sum_circle``` with ```bkgann```? 

I've been playing around today with the segmentation map in an attempt to do this manually. I am using masked arrays to generate a (0 | 1) mask that contains the sky and the target star only (both set to 0) and then feeding that to sum_circle. This is what I have done:

```python
target_sky_only = np.ma.masked_where(((seg_map > 0) & (seg_map != star_id+1)), seg_map)
binary_mask = target_sky_only.mask.astype(np.int32)
fm, fem, flagm = sep.sum_circle(data, i, j, 5, subpix=0, bkgann=(15, 20), gain=1.22, mask=binary_mask, maskthresh=0.0)
```
I assign all other pixels (stars etc) a value 1 and then use  ```maskthres=0.0``` which, if I understand correctly, should ignore all pixels except the target and the sky. I just wanted to check that it is not already being done before I continue. 

Cheers
James

**Comment by kbarbary** [comment]
The aperture functions do not automatically account for other objects that might affect the sky annulus (or the aperture itself). What you're doing sounds reasonable.

**Comment by jmccormac01** [comment]
Excellent thanks very much for confirming.
