### ISSUE TITLE
Exponential Profile extraction?

### ISSUE THREAD

**Issue by MickaelRigault** [kbarbary/sep#49]
Would it be possible to add a new extraction profile (in addition to circle, ellipse and so on) to enable to get exponential weighted extraction following e.g. 
http://www.sdss.org/dr12/algorithms/magnitudes/#mag_model

**Comment by kbarbary** [comment]
SDSS model mags are pretty different from aperture magnitudes because the model is convolved with the image PSF and there's a joint fit between images in different bands. So I think the issues in #36 apply here.

**Comment by MickaelRigault** [comment]
I understand.
