### ISSUE TITLE
Background: input array dtype not supported: int16

### ISSUE THREAD

**Issue by ricardogando** [kbarbary/sep#50]
Hi, 
I downloaded a FITS image from ds9 (for teaching purposes) and wanted to analyze it with sep. Going through the tutorial (I used fitsio) I got the following at the background part.

`bkg = sep.Background(data)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-38-e95be84d2529> in <module>()
----> 1 bkg = sep.Background(data)

sep.pyx in sep.Background.__cinit__ (sep.c:4492)()

sep.pyx in sep._parse_arrays (sep.c:3672)()

sep.pyx in sep._get_sep_dtype (sep.c:2908)()

ValueError: input array dtype not supported: int16
`
Any ideas?
Thanks,
Ricardo

**Comment by kbarbary** [comment]
Try converting your data to a supported type, such as int32:
```
data = numpy.asarray(data, dtype=np.int32)
```

**Comment by ricardogando** [comment]
Thanks, it worked!
