### ISSUE TITLE
Consider adding SEP to ascl.net

### ISSUE THREAD

**Issue by juandesant** [kbarbary/sep#66]
Hi, just a quick note that it would be nice to have SEP in the Astronomical Source Code Library (ASCL) repository, and making a quick entry would be quite useful. I know there is already a JOSS paper on SEP, but it would help a lot with the discovery if there was a relevant entry on https://ascl.net, especially if there are also science papers written on it.

I am happy to do the draft entry if you think that is useful.

Cheers!

**Comment by kbarbary** [comment]
If you want to submit an entry for SEP, that would be great!

**Comment by juandesant** [comment]
Already done 😉

https://ascl.net/code/v/2108

Please, feel free to contact ASCL if you think there is need for corrections. Cheers!

**Comment by kbarbary** [comment]
Thank you, that looks great!
