### ISSUE TITLE
flux estimated by SEP and that by SExtractor are not matching

### ISSUE THREAD

**Issue by astrosumit** [kbarbary/sep#68]
The Kron flux estimated using SEP and that using SExtractor are not matching significantly. May be I have done something wrong. Any help will be appreciated. This is my code:

```python
import numpy as np    
import sep    
from astropy.io import fits
from astropy import wcs

filename='map.fits'
hdu = fits.open(filename)
hdu.verify('fix')
h = hdu[0].header
img = hdu[0].data[0,0,:,:]

img = img.byteswap().newbyteorder()
bkg = sep.Background(img)
data_sub = img - bkg

objects = sep.extract(data_sub, thresh=10.0, err=bkg.globalrms, mask=None, minarea=10, filter_type='matched', deblend_nthresh=32, deblend_cont=0.05, clean=True, clean_param=1.0, segmentation_map=False)

kronrad, krflag = sep.kron_radius(data_sub, objects['x'], objects['y'], objects['a'], objects['b'], objects['theta'], 6)

for i in range(len(objects)):
    if kronrad[i]>=3.5:
        r_kron=kronrad[i]
    else:
        r_kron=3.5
    print(r_kron)

flux_auto, fluxerr_auto,flag = sep.sum_ellipse(data_sub, objects['x'], objects['y'], objects['a'], objects['b'], objects['theta'], 2.5*r_kron, bkgann=None, gain=1.0, subpix=5)
```

Thanks...

**Comment by kbarbary** [comment]
It's hard to say what's wrong without knowing what parameters your used to run SExtractor, or knowing what the differences are. 

There *is* an automated test to ensure that the SEP output matches SExtractor on a test image. It might help you to look at how the test is run. You can find the test [here](https://github.com/kbarbary/sep/blob/3a01b1d7527d620464d13ba44cdf8c1f217e9fc9/test.py#L205) and you can find the parameters used to run SExtractor [here](https://github.com/kbarbary/sep/tree/3a01b1d7527d620464d13ba44cdf8c1f217e9fc9/data).  Note that the parameters used in `sep.extract` in the test (see [here](https://github.com/kbarbary/sep/blob/3a01b1d7527d620464d13ba44cdf8c1f217e9fc9/test.py#L155)) are different than the ones you're using. That could be one difference.

**Comment by kbarbary** [comment]
Also, I just noticed that you're passing `2.5 * r_kron` to `sep.sum_ellipse()`. After the for-loop, `r_kron` is a scalar that is either 3.5 or the kron radius of the last object. This is probably not what you're trying to do.

**Comment by astrosumit** [comment]
Thanks for your reply. I checked the test program and everything was good.  And I found the problem with my code. I used MASK_TYPE=CORRECT in SExtractor, while there is no such parameter in SEP, probably SEP uses MASK_TYPE=NONE. The MASK_TYPE=CORRECT option is very useful if you are dealing with crowded field. Could you please tell me a similar option in SEP? Thanks in advance...

**Comment by kbarbary** [comment]
See #60.
