### ISSUE TITLE
Questions about Crowded fields

### ISSUE THREAD

**Issue by cmccully** [kbarbary/sep#72]
I have been running into issues extracting photometry in crowded fields near the buldge and had a few questions about if it was possible to tune SEP to perform better in these fields.

One question is that the maximum number of objects per level is hard coded to 1024.
#define	NSONMAX	1024  /* max. number per level */
Is that required, or could that be parameterized like set_pixextract()?  

One way to not have SEP crash is to raise the detection threshold considerably. That works for a basic extraction of astrometry, but I was hoping to be able to go deeper in the image.  Setting the detection threshold high in these fields can cause strange issues if the seeing/focus of the image is not great. 

Deblending in general is quite a challenge in these crowded fields so it would be nice to set the deblend threshold quite low, but that seems to hit a crash quite quickly.

Memory is not an issue on the machine we are using and we don't mind if the processing takes significant time. 

Any suggestions? Any ideas are welcome.

**Comment by cmccully** [comment]
@kbarbary any thoughts?

**Comment by kbarbary** [comment]
Is it a configurable parameter in Source Extractor? It could have changed since I forked the SEP codebase.

Without looking, I'm guessing it could be made configurable in SEP, either with a global (like `set_pixextract()`) or with a keyword argument. I'll take a closer look tonight or tomorrow. I don't have time to implement, but I could advise.

**Comment by cmccully** [comment]
It doesn't appear to be configurable by the user. It appears to dynamically figure out what it needs somehow. I haven't looked deeply enough in the code to have a full understanding.
