### ISSUE TITLE
dtype not recognized/unsupported

### ISSUE THREAD

**Issue by nightrook779** [kbarbary/sep#74]
I am following the example in tutorial.
I am getting a dtype not recognized/unsupported exception at
```
bkg_image = bkg.back()
```

when I execute
```
bkg = sep.Background(data)
bkg_image = bkg.back()
```

What am I doing wrong?

**Comment by kbarbary** [comment]
What is the dtype of `data`? You can see this by doing `data.dtype`.

**Comment by nightrook779** [comment]
dtype of data:
`<class 'numpy.ndarray'>`

dtype of bkg:
`<class 'numpy.ndarray'>`

**Comment by kbarbary** [comment]
You should see something like `dtype('float64')`. I'm not sure how you could get that result for `data.dtype`. Is `data` a numpy array? Maybe you could post a minimal example.

**Comment by nightrook779** [comment]
Oh. I see what happened.
I am using openCV to import and manipulate the image, since I can't use fitsio. My bad.
Any alternatives/thoughts on how to do this?

**Comment by kbarbary** [comment]
Regardless of the method you use to read the data, you need to get it in the form of a 2-d numpy array of floats or ints. This should be possible with opencv, but I'm not that familiar with the library.

**Comment by nightrook779** [comment]
Alright I was able to get the code working. Whats happening is that since I am reading jpeg files, numpy array is uint8. Converting to float64 fixed the issue. Code I used:
`
data = cv2.imread('pinwheel.jpg')
data = cv2.cvtColor(data,cv2.COLOR_BGR2GRAY)
data = data.astype(np.float64)
`
