### ISSUE TITLE
Running SEP with Python 3.7?

### ISSUE THREAD

**Issue by HelenUsher** [kbarbary/sep#76]
I've just tried to install, but failed as I'm using python 3.7.  Can this incompatibility be resolved?

Many thanks

Helen

**Comment by floydie7** [comment]
I'm currently running SEP on Python 3.7.6. What was the error that you received?

**Comment by HelenUsher** [comment]
Thanks for your reply Benjamin.  I will check the exact error message
tomorrow, but it was on installing and was about compatibility (it only
listed 3.5, 3.6 as compatible...

**Comment by HelenUsher** [comment]
Hi Benjamin,
Here's the error message

UnsatisfiableError: The following specifications were found

to be incompatible with the existing python installation in your environment:




Specifications:




  - sep -> python[version='2.7.*|3.4.*|3.5.*|3.6.*']



Your python: python=3.7
Thanks
Helen
    On Wednesday, 29 April 2020, 00:06:42 BST, Benjamin Floyd <notifications@github.com> wrote:  
 
 


I'm currently running SEP on Python 3.7.6. What was the error that you received?

**Comment by floydie7** [comment]
It sounds like however you're managing your python packages might be outdated. I might recommend using conda if you're not already. Using the conda-forge channel I was able to install it easily. Searching "sep" in conda shows that version 1.0.3 should even work on Python 3.8.

Try making an environment with the following:
`conda create -n sep-test python=3.7 -c conda-forge sep`

**Comment by HelenUsher** [comment]
Thanks again Benjamin.  I was using Openastronomy, but changing to conda-forge solved the issue and I am now installed 
Helen
    On Wednesday, 29 April 2020, 20:44:08 BST, Benjamin Floyd <notifications@github.com> wrote:  
 
 


It sounds like however you're managing your python packages might be outdated. I might recommend using conda if you're not already. Using the conda-forge channel I was able to install it easily. Searching "sep" in conda shows that version 1.0.3 should even work on Python 3.8.

Try making an environment with the following:
conda create -n sep-test python=3.7 -c conda-forge sep

**Comment by kbarbary** [comment]
Thanks for helping resolve this, @floydie7!
