### ISSUE TITLE
Threading problem of c library.

### ISSUE THREAD

**Issue by fockez** [kbarbary/sep#81]
Definitely sep is a good idea, especially the c library makes it easier to build a customized "sextractor", but now I met some performance problem. Because of the widely use of multi core CPU, obviously the multi threading is a efficient way.
But after some test, multi threading failed, maybe the reason of some global variables. 
So, is that possible to make a library suitable for multi-threading, or is that possible to support openmp in sep?

**Comment by kbarbary** [comment]
Thanks!

I believe SExtractor (and SEP by extension) do indeed have some global modified state in the `extract` functionality. Unfortunately this is pretty "baked in" to the design and it would likely be a major rewrite to make it thread safe or use openmp.  It also might be tricky to divide work on a single image between threads. An alternative to take advantage of multiple cores would of course be to use multi-processing. You must be working on very large images if you're running into performance problems!

I would expect that the photometry functions (and possibly background estimation) are thread safe.

**Comment by fockez** [comment]
Thank you for the reply. Base on our simple test, the consumption of deblending is very high, because we are dealing very large field images and star field is too crowded. I believe this part can be parallelized.
We have too many images to reduce in one C program, it's not easy to use multi-processing to replace the multi-threading while keep the efficient.

**Comment by knro** [comment]
I was about to open a new issue on this very topic. I was trying to use multiple threads for SEP and that failed miserably due to many static global variables around. This was designed for the era of single threaded programs and certainly multi-threading was not a concern.

Would could conceivably partition a large image into discrete regions and run Sep on each to merge the results of each thread later.

**Comment by RReverser** [comment]
Has anyone tried to literally replace all those `static` with `thread_local`? In C11 compilation mode, there is a chance that might just work.

**Comment by RReverser** [comment]
(well, also need to check that it's not using any non-thread-safe system functions)

**Comment by RReverser** [comment]
In case someone on this thread also wants to test it, I've made the library thread-safe in #109.
