### ISSUE TITLE
Bump pypi version

### ISSUE THREAD

**Issue by Lyalpha** [kbarbary/sep#83]
`pip install sep`  will still install `1.0.3`.

I see there is an important change in `1.10` (masking of other sources when doing photometry), could the latest release be bumped to this version? (Assuming the changes are working as intended - I haven't tried them myself yet).

**Comment by kbarbary** [comment]
Thanks for the reminder. I've been meaning to do this. (The latest version should be `1.1.0` by the way; `1.10` was a typo.) There are some build system changes (like #78) that need to get finished before a release. I'll try to find time this week.

**Comment by kbarbary** [comment]
Finally released v1.1.0! Let me know if you have any problems.
